### ISSUE TITLE
Permission Denied, Not Found

### ISSUE THREAD

**Issue by gudenau** [Magisk-Modules-Repo/fontrevival#10]
I installed Font Manager on my Pixel 4 XL and when running manage_fonts after the installation and reboot it isn't executable. When going into the module directory and adding the executable bit the script can't find the provided bash binary.

Log:
```
Wed Jan  5 19:17:54 2022 Module: FontManager vv5.4.4
Wed Jan  5 19:17:54 2022 Device: google Pixel 4 XL (coral)
Wed Jan  5 19:17:54 2022 ROM: RQ1A.210105.003, sdk
```

**Comment by sid-tanwar** [comment]
Hi, go to this link -https://www.androidacy.com/downloads/?fm_rdme_links=&view=%2540Magisk-Modules%2540Font_Manager and download the latest version which is 5.5.6 and that will solve your problem.

**Comment by gudenau** [comment]
Thank you.
