### ISSUE TITLE
Bariol Font Broken

### ISSUE THREAD

**Issue by alroy214** [Magisk-Modules-Repo/fontrevival#3]
![Screenshot_20210508-091846_Chrome](https://user-images.githubusercontent.com/31711733/117529118-69f20000-afde-11eb-8fd4-d779faed04ec.jpg)

Can you fix the bariol Font in the repo? There's bariol fonts that won't break the emojis

**Comment by androidacy** [comment]
If you can link to an example we'll be happy to look at it.

**Comment by alroy214** [comment]
I think the font itself is just broken as the emojis are off cut,
here is the official font website: https://www.atipofoundry.com/fonts/bariol
maybe that will work, I don't know, been using the font for years but this time it's just off with the icons
