### ISSUE TITLE
[Bug] Download URL uses bad format

### ISSUE THREAD

**Issue by dhruvkrishnavaid** [Magisk-Modules-Repo/fontrevival#4]
**Description**
Everytime, I try to install, it says installation failed. So, I checked the logs. I found that the download URL uses a bad format.

**System info**
Magisk version 23.0
Stock Android 5.1 with Magisk patched boot.img

**Logs**
[/sdcard/FontManager/logs/install.log](https://github.com/Magisk-Modules-Repo/fontrevival/files/6476422/install.log) (see line 32)
[/sdcard/Download/magisk_install_log_2021-05-14T09:12:41Z.log](https://github.com/Magisk-Modules-Repo/fontrevival/files/6476432/magisk_install_log_2021-05-14T09.12.41Z.log)

Hope that the issue will be fixed soon 🙂

**Comment by androidacy** [comment]
Cannot reproduce. Try redownloading the module.

**Comment by dhruvkrishnavaid** [comment]
Tried redownloading a hundred times. Didn't work, at least for me. Every time the same bad url error occurs. Can you provide me the actual http url so that I can manually install the module and download the font list.

**Comment by androidacy** [comment]
Seeing as _nobody else_ has your issue, something is wrong and besides that, our API is not intended for public use (which is where font manager gets everything) but for our apps and services.

Once again, make sure to clean install the module. There's a possibility you have another module interfering. I got one feel certain if this wasn't just a you issue, we'd have heard about it, and testing would have shown it.

And I will reiterate: if you want your next issue not closed immediately, provide the very useful logs put out to /sdcard/FontManager/logs
